export enum OsEventType {
  SCM_SUPPLY_RECEIVED = 'SCM.SUPPLY_RECEIVED',
  SCM_SALE_POSTED = 'SCM.SALE_POSTED',
  INVENTORY_STOCK_CHANGED = 'INVENTORY.STOCK_CHANGED',
  FINANCE_SALES_DOCUMENT_POSTED = 'FINANCE.SALES_DOCUMENT_POSTED',
  INVENTORY_ADJUSTMENT_POSTED = 'INVENTORY.ADJUSTMENT_POSTED',
  INVENTORY_TRANSFER_POSTED = 'INVENTORY.TRANSFER_POSTED',
}
